config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :users
  resources :tags, only: [:index, :show]
  root to: 'homepage#index'
  get '/:username' => 'links#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_taggable
  belongs_to :user
  validates :link, :presence => true, :allow_blank => false, uniqueness: { scope: :user_id,
    message: "already present" }
  validates :description, :presence => true, :allow_blank => false, :length => { in:5..140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :uniqueness => true, :presence => true, length: { in: 5..20 }
  validates_format_of :username, with: /\A[a-zA-Z0-9]+\z/

  attr_accessor :login

  has_many :links

  # overwite for user login
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # before_filter :authenticate_user!
  def index
    @link = Link.new
    @user_id = User.find_by_username(params[:username])
    if user_signed_in? and @user_id == current_user
      @links = Link.where(:user_id => current_user)
    else
      @links = Link.joins(:user).where(users: { username: params[:username] }, links: { link_type: 'public' })
    end

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @links }
      format.js
    end
  end

  def show

  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    if user_signed_in?
      redirect_to :controller => 'links', :action => 'index', :username => User.find_by_id(current_user).username
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # before_filter :authenticate_user!
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @link = Link.new
    @user = User.find_by_username(params[:username])
    if user_signed_in? and @user == current_user
      @links = current_user.links.order('created_at DESC').page(params[:page]).per_page(15)
      # @links = current_user.links.reverse
    else
      @links = @user.links.where(:link_type => 'public').order('created_at DESC').page(params[:page]).per_page(15)
      # @links = @user.links.where(:link_type => 'public').reverse
    end

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @links }
      format.js
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id


    respond_to do |format|
      if @link.save
        format.json { render :show, status: :created, location: @link }
        format.js
      else
        # puts @link.errors.full_messages
        format.json { render json: @link.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:user_id, :link, :link_type, :description, :tag_list)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @links_tagged = Links.tagged_with(@tag.name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/dashboard/create.js.erb
$('.link_share').append('<% j render @link %>');

app/views/dashboard/index.html.erb
<h1>Welcome to Dashboard</h1>
<!-- <p id="notice"><%= notice %></p> -->

<!-- <h4>Your shared links</h4> -->
<%= form_for(@link, remote: true) do |f| %>
  <div class="link_share">
    <div class="field" style="display: inline">
      <%= f.label :link %>
      <%= f.text_field :link %>
      <%= f.label :link_type %>
      <%= f.text_field :link_type %>
    </div>
    <div class="actions" style="display: inline">
      <%= f.submit 'Share'%>
    </div>
  </div>
  <% end %>

<% if @links.empty? %>
  <p>No Links</p>
<% else %>
  <table>
    <thead>
      <tr>
        <!-- <th>User</th> -->
        <th>Link</th>
        <th>Link type</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @links.each do |link| %>
      <tr>
        <!-- <td><%= link.user_id %></td> -->
        <td><%= link.link %></td>
        <td><%= link.link_type %></td>
        <!-- <td><%#= link_to 'Show', link %></td>
        <td><%#= link_to 'Edit', edit_link_path(link) %></td>
        <td><%#= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
      <% end %>
    </tbody>
    </table>
  <% end %>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/dashboard/show.html.erb
<h1>Welcome to Dashboard</h1>
<!-- <p id="notice"><%= notice %></p> -->

<!-- <h1>Listing Links in dashboard</h1> -->

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Link</th>
      <th>Link type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <!-- <td><%= link.user_id %></td> -->
        <td><%= link.link %></td>
        <td><%= link.link_type %></td>
        <!-- <td><%#= link_to 'Show', link %></td>
        <td><%#= link_to 'Edit', edit_link_path(link) %></td>
        <td><%#= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/homepage/index.html.erb
<h1>Welcome to Homepage</h1>
<%= render "devise/registrations/form" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="container">
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<%= link_to image_tag("logo.png"), '/', id: "logo_img" %>
  <%= link_to "ShareIt", '/', id: "logo" %>
  <div class="container">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home",   '#' %></li>
      <li><%= link_to "Help",   '#' %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
    </div>
</header>

app/views/layouts/_user_widget.html.erb
<% if !user_signed_in? %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

 <!-- <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 -->

<%= yield %>

<%= render 'layouts/footer' %>
<% if controller_name != 'sessions' && controller_name != 'registrations' && controller_name != 'homepage' %>
  <%= render 'layouts/user_widget' %>
<% end %>


</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link, remote: true) do |f| %>
  <div class="link_share">
    <div class="field" style="display: inline">
      <%= f.text_field :description, :class => "link_box", placeholder: 'Add Description Here' %>
      &nbsp&nbsp
      <%= f.text_field :link, :class => "link_box", placeholder: 'Paste your link' %>
      &nbsp&nbsp
      <%= f.text_field :tag_list, placeholder: 'tags' %><br/><br/>
      &nbsp&nbsp
      <%= f.label :link_type, "public", :value => "public" %>
      <%= f.radio_button :link_type, "public", :checked => true %>
      <%= f.label :link_type, "private", :value => "private" %>
      <%= f.radio_button :link_type, "private" %>
    </div>
    <div class="actions" style="display: inline">
      <%= f.submit 'Share', class: 'btn btn-lg btn-primary'%>
    </div>
  </div>
  <% end %>

app/views/links/_link.html.erb
<tr>
  <td id="link_data"><%= link_to(link.description, "http://"+link.link, { target: '_blank' }) %></td>
  <td id="link_opt"><%= link.link_type %></td>
  <% if user_signed_in? and link.user.username == current_user.username %>
    <td id="link_opt"><%= link_to 'Edit', edit_link_path(link) %>
    <td id="link_opt"><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/links/create.js.erb
<% if @link.errors.present? %>
  <% @link.errors.full_messages.each do |msg| %>
    $('#notice').html("<%= msg %>")
  <% end %>
<% else %>
$('.link_table').prepend('<%= j render @link %>');
$('#notice').html('Link saved successfully');
<% end %>
$('.link_box').val('');

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>
<div class="center">
<h1>Welcome to Share it</h1><br><br>
<% if @user == current_user %>
  <%= render 'form' %>
  <br><br>
<% end %>
</div>

<% if @links.empty? %>
  <p>No Links</p>
<% else %>
  <table id="main_table">
    <thead>
      <tr>
        <th id="link_col">Link Description</th>
        <th colspan="100">Link type</th>
      </tr>
    </thead>
    <tbody class="link_table">
      <% @links.each do |link| %>
        <%= render link %>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>
<%= will_paginate @links, renderer: BootstrapPagination::Rails %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @link.user_id %>
</p>

<p>
  <strong>Link:</strong>
  <%= @link.link %>
</p>

<p>
  <strong>Link type:</strong>
  <%= @link.link_type %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/tags/_tag.html.erb
<%= tag.name %>
<%#= link_to tag.name, tag_path(tag) %>

app/views/tags/index.html.erb
<h1>Tags</h1>
<% if @tags.empty? %>
  <p>No Tags</p>
<% else %>
  <% @tags.each do |tag| %>
    <%#= tag.name %>
    <%= render tag %>
  <% end %>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<div><%= render @links %></div>